### ISSUE TITLE
NDepend Action not comparing to baselines

### ISSUE THREAD

**Issue by togabrennan** [ndepend/ndepend-action#2]
I have a ndepend-action running and our main branch is `nextrelease`. NDepend analysis' exist on both the `nextrelease` branch and on our feature branches. The ndepend action never detects the baseline and instead always errors out with the following error:

`No baseline to compare found for :nextrelease_recent`

![image](https://github.com/ndepend/ndepend-action/assets/46493523/8141c30c-c891-4438-808e-b2a0cfe5339d)

Config:

```yaml
     - name: NDepend
        uses: ndepend/ndepend-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          license: ${{ secrets.NDependLicense }}
          baseline: nextrelease_recent
```
