### ISSUE TITLE
No baseline to compare found

### ISSUE THREAD

**Issue by pkmetski** [ndepend/ndepend-action#6]
I have been trying to setup the NDepend Github Action following [this](https://www.ndepend.com/docs/ndepend-github-action) guide. Here is what my setup looks like:

```
    - name: NDepend code analysis
      uses: ndepend/ndepend-action@v2
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        license: ${{ secrets.NDEPEND_LICENSE }}
        customconfig: my project.ndproj
        stopIfQGFailed: false
        baseline: setup-ndepend_recent
```
 My feature branch is called `setup-ndepend`. Furthermore, I have changing the value of "baseline" to "recent", and 39 (an existing run number). In all of these cases, running the action results in `Warning: No baseline to compare found for ...`
My repo is private, and the artifacts (ndepend, ndependtrned) do exist - the action has been run multiple times on the branch in question. I have also tried with `ndepend/ndepend-action@v1`, but the result is the same.

I noticed the [same issue](https://github.com/ndepend/ndepend-action/issues/2) reported some time ago, and it was then fixed.

Can you please advise?
